baseURL = 'https://alir.me/'
languageCode = 'en-us'
title = 'Ali Rathore - AI Consultant & Agent Builder'
theme = ''

[params]
  description = "AI Consultant specializing in agents, automation, and AI-native solutions. Enterprise AI transformation, custom agent development, and team training."
  keywords = "AI consultant, AI agents, automation, machine learning, enterprise AI, AI implementation"
  author = "Ali Rathore"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/#about"
    weight = 10
  
  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/#experience"
    weight = 20
  
  [[menu.main]]
    identifier = "expertise"
    name = "Expertise"
    url = "/#expertise"
    weight = 30
  
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/#services"
    weight = 40
  
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/#portfolio"
    weight = 50
  
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/#contact"
    weight = 60
